

name: CD to GitHub Releases

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@1.0.1
      with:
        # GitHub token
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Local file to upload
        file: build/libs/search-on-github-plugin-1.0-SNAPSHOT.jar
        # Name of the asset
        asset_name: Plugin JAR
        # Tag to use as a release
        tag: ${{ github.ref }}
        # Overwrite the release in case it already exists
        overwrite: false
